### ISSUE TITLE
installation in amazon linux 2 error (python3-yaml package)

### ISSUE THREAD

**Issue by Hokwang** [newrelic/infrastructure-agent-ansible#171] opened 2022-03-14 16:43 UTC
[NOTE]: installation in amazon linux 2 error (python3-yaml package)

## Description
[NOTE]: 
```
TASK [newrelic.newrelic-infra : ensure python3-yaml is installed] ***************************************
fatal: [i-03b683927f52ea8e3]: FAILED! => {"changed": false, "msg": "No package matching 'python3-yaml' found available, installed or updated", "rc": 126, "results": ["No package matching 'python3-yaml' found available, installed or updated"]}
```

in the server,
```
# yum list | grep -i py | grep -i yaml
PyYAML.x86_64                           3.10-11.amzn2.0.2             installed
python2-avocado-plugins-loader-yaml.noarch
python2-avocado-plugins-varianter-yaml-to-mux.noarch
python2-pyyaml.noarch                   3.10-0.el7                    epel
python2-ruamel-yaml.x86_64              0.13.14-2.el7                 epel
python2-yamlordereddictloader.noarch    0.4.0-2.el7                   epel
python36-PyYAML.x86_64                  3.13-1.el7                    epel
python36-ruamel-yaml.x86_64             0.13.14-2.el7                 epel
python36-yamlordereddictloader.noarch   0.4.0-2.el7                   epel
```

there's no `python3-yaml` package.

I think you need to fix `ensure python3-yaml is installed` step code for variable OS.

## Your Environment
AWS EC2 using amazon linux 2

**Comment by Hokwang** [comment] 2022-03-16 03:36
@sdewitt-newrelic Please check this issue.

**Comment by codrinh** [comment] 2022-03-23 11:02
Same issues occurs on centos-7 with python3.6.8

How to download and install the `python36-PyYAML` package ( still requires local role alteration )

https://stackoverflow.com/a/61197215

Maybe using a package that is available with `pip` would provide more consistency across different distributions ( PyYaml ).

**Comment by zeffron** [comment] 2022-08-26 20:01
This fix is both not correct and incomplete. On RedHat (at least Fedora and Amazon Linux 2), the issue is not that PyYAML is not available, but that the package name is different. The package name is `python3-pyyaml`.

Also, the merged fix uses `pip3` but does not ensure it's installed.

Please refix by installing the correct package name instead of using pip.

**Comment by karlforster** [comment] 2022-10-18 15:04
Can this be fixed please, its also causing us issues using Ansible for our builds to install NR.


> This fix is both not correct and incomplete. On RedHat (at least Fedora and Amazon Linux 2), the issue is not that PyYAML is not available, but that the package name is different. The package name is `python3-pyyaml`.
> 
> Also, the merged fix uses `pip3` but does not ensure it's installed.
> 
> Please refix by installing the correct package name instead of using pip.

**Comment by davidgit** [comment] 2022-10-19 10:46
@karlforster We planned this work for late November. We'll keep you updated

**Comment by karlforster** [comment] 2022-10-19 21:59
@davidgit - Hello, are there any workaround to this I can use? Otherwise I will have to change our ansible code to install NR agent to use a shell script.

**Comment by zeffron** [comment] 2022-10-20 01:04
For a workaround, you can have your ansible code install the `python3-pip` package prior to running the ansible role.

**Comment by karlforster** [comment] 2022-10-20 10:07
@zeffron - the workaround isnt working.
verified the python-3 pip is installed. 
Package python3-pip-20.2.2-1.amzn2.0.3.noarch already installed and latest version

Surely this is a simple change in the code to update the package from `python3-yaml` to `python3-pyyaml`

**Comment by karlforster** [comment] 2022-10-20 11:36
I have managed to get past the issue
we were pinned in our ansible scripts to a particular version of NR agent.
**ansible-galaxy install newrelic.newrelic-infra,0.10.3**

Removing the 0.10.3 has allowed the process to go through.

**Closed** 2022-10-20 14:13 UTC
Labels: support

**Comment by zeffron** [comment] 2022-10-20 18:21
@rogercoll Please reopen. I never said I was using Amazon Linux. We use Fedora, and not all spins/installs of Fedora (especially ones using custom kickstart files) include pip3 by default.
