### ISSUE TITLE
Can't install the New Relic Infrastructure agent

### ISSUE THREAD

**Issue by jpmontez** [newrelic/infrastructure-agent-ansible#55] opened 2018-10-31 18:13 UTC
When attempting to install the agent via the Ansible Galaxy role, I receive the following error:
```
fatal: [<omitted>]: FAILED! => changed=false
  cache_update_time: 1541008792
  cache_updated: false
  invocation:
    module_args:
      allow_unauthenticated: false
      autoclean: false
      autoremove: false
      cache_valid_time: 0
      deb: null
      default_release: null
      dpkg_options: force-confdef,force-confold
      force: false
      force_apt_get: false
      install_recommends: null
      name: newrelic-infra*
      only_upgrade: false
      package:
      - newrelic-infra*
      purge: false
      state: latest
      update_cache: null
      upgrade: null
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"     install 'newrelic-infra-integrations' 'newrelic-infra-rootless'' failed: E: Unable to correct problems, you have held broken packages.
  rc: 100
  stderr: |-
    E: Unable to correct problems, you have held broken packages.
  stderr_lines:
  - 'E: Unable to correct problems, you have held broken packages.'
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     newrelic-infra-integrations : Depends: nri-apache but it is not going to be installed
                                   Depends: nri-cassandra (>= 2.0.0) but it is not going to be installed
                                   Depends: nri-mysql but it is not going to be installed
                                   Depends: nri-nginx but it is not going to be installed
                                   Depends: nri-redis but it is not going to be installed
  stdout_lines: <omitted>
```

When I follow the agent repository link, it's empty:
```
ok: [<omitted>] => changed=false
  diff: {}
  invocation:
    module_args:
      codename: null
      filename: null
      install_python_apt: true
      mode: null
      repo: deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt trusty main
      state: present
      update_cache: true
      validate_certs: true
  repo: deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt trusty main
  state: present
```

**Comment by nwalke** [comment] 2018-10-31 21:31
This is also happening on RedHat:
```
    amazon-ebs: TASK [nrinfragent : install agent] *********************************************
    amazon-ebs: fatal: [127.0.0.1]: FAILED! => {"changed": true, "msg": "Error: newrelic-infra-rootless conflicts with newrelic-infra-1.0.1033-1.x86_64\n", "rc": 1, "results": ["Loaded plugins: amazon-id, rhui-lb, search-disabled-repos\nPackage newrelic-infra-integrations-beta is obsoleted by newrelic-infra-integrations, trying to install newrelic-infra-integrations-1.6.0-1.x86_64 instead\nResolving Dependencies\n--> Running transaction check\n---> Package newrelic-infra.x86_64 0:1.0.1019-1 will be updated\n---> Package newrelic-infra.x86_64 0:1.0.1033-1 will be an update\n---> Package newrelic-infra-integrations.x86_64 0:1.6.0-1 will be installed\n--> Processing Dependency: nri-cassandra >= 2.0.0 for package: newrelic-infra-integrations-1.6.0-1.x86_64\n--> Processing Dependency: nri-redis for package: newrelic-infra-integrations-1.6.0-1.x86_64\n--> Processing Dependency: nri-nginx for package: newrelic-infra-integrations-1.6.0-1.x86_64\n--> Processing Dependency: nri-mysql for package: newrelic-infra-integrations-1.6.0-1.x86_64\n--> Processing Dependency: nri-apache for package: newrelic-infra-integrations-1.6.0-1.x86_64\n---> Package newrelic-infra-rootless.x86_64 0:0.0.rootless_rc1.15-1 will be installed\n--> Running transaction check\n---> Package nri-apache.x86_64 0:1.1.2-1 will be installed\n---> Package nri-cassandra.x86_64 0:2.0.2-1 will be installed\n--> Processing Dependency: nrjmx for package: nri-cassandra-2.0.2-1.x86_64\n---> Package nri-mysql.x86_64 0:1.1.2-1 will be installed\n---> Package nri-nginx.x86_64 0:1.0.1-1 will be installed\n---> Package nri-redis.x86_64 0:1.0.1-1 will be installed\n--> Running transaction check\n---> Package nrjmx.x86_64 0:1.0.2-1 will be installed\n--> Processing Conflict: newrelic-infra-rootless-0.0.rootless_rc1.15-1.x86_64 conflicts newrelic-infra\n--> Finished Dependency Resolution\n--> Finding unneeded leftover dependencies\nFound and removing 0 unneeded dependencies\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
```

This should be seen as a production issue :/

**Comment by jpmontez** [comment] 2018-10-31 23:12
@nwalke I’ll try that and report back. Thanks!

**Comment by danrough** [comment] 2018-11-01 08:07
Suffering the same problem, when trying to install using the Ansible Galaxy role targetting a Debian Stretch (9.5) server.

I'm calling the role as follows:

``` 
- name: newrelic.newrelic-infra
      become: yes
      vars:
        nrinfragent_os_name: Debian
        nrinfragent_os_version: stretch
        nrinfragent_config:
          license_key: LICENSE_KEY
```

and the response I'm receiving is as follows:

```
FAILED! => {"cache_update_time": 1541018866, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'newrelic-infra' 'newrelic-infra-integrations' 'newrelic-infra-rootless'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n newrelic-infra-rootless : Conflicts: newrelic-infra but 1.0.1033 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " newrelic-infra-rootless : Conflicts: newrelic-infra but 1.0.1033 is to be installed"]}
```

I've tried deleting the Galaxy role, to ensure that I have the latest version, but that has had no effect.

**Comment by kidk** [comment] 2018-11-01 10:59
It seems `newrelic-infra-integrations` conflicts with `newrelic-infra-rootless`.

```
samuel@build:~$ sudo apt-get install newrelic-infra-integrations
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  newrelic-infra nri-apache nri-cassandra nri-mysql nri-nginx nri-redis nrjmx
The following packages will be REMOVED:
  newrelic-infra-rootless
```

**Comment by xino12** [comment] 2018-11-01 11:38
Hi, are you installing newrelic-infra* ?
I've been testing the galaxy role in both centos7 and it's working for me.

Could you check that you're not installing using a wildcard? There could be some problems if you try to install newrelic-infra-rootless and you have newrelic-infra package installed as you have seen in the logs.
I'm still investigating what's the problem with Debian based OS. And post a workaround here. 

I'm sorry for the inconveniences.

**Comment by xino12** [comment] 2018-11-01 11:54
Okay, I've found the root cause of the failure.

What happens with Debian based OS is that there is a varibale that if it's not set it's converted to *
That makes our role to fail. 
Until we come up with a proper fix you can use a workaround setting this variable to ""

Tha name of the variable is: nrinfragent_version

So you can either setup to "" in your vars file or you can run the command like this.

ansible-playbook  -i <INVENTORY_FILE> playbook.yml   **--extra-vars "nrinfragent_version="**

With that the role won't try to install newrelic-infra-rootless package and won't fail.

Again, sorry for the inconvenience.

**Comment by jpmontez** [comment] 2018-11-01 12:17
@xino12 That works!

Also, ensuring the role is completely up-to-date and re-running the agent installation is now working for me this morning.

**Comment by slaymance** [comment] 2018-11-02 19:00
Also identified this same issue on RHEL 7.5 and the fix suggested by @xino12 works.

**Comment by xino12** [comment] 2018-11-13 10:00
I'm closing this since it has been fixed in new versions.

**Closed** 2018-11-13 10:00 UTC
