### ISSUE TITLE
didn't this role work for Xenial Xerus (Ubuntu 16.04.3 LTS)

### ISSUE THREAD

**Issue by habtamua** [newrelic/infrastructure-agent-ansible#21] opened 2017-11-08 20:19 UTC
I have been using this for many distributions, and it worked, have not see any issue so far, but recently i upgrade some boxes to **Xenial Xerus (Ubuntu 16.04.3 LTS**) which make the newrelic infrastructure to start failing or missing some library, i tried to reinstall using ansible and almost all task run perfect except the last tasks - name: setup agent service`, I also tried to start the service manually that didn't work ask well,

Here I added all info if that helps,
```

$ sudo systemctl status newrelic-infra
● newrelic-infra.service
   Loaded: not-found (Reason: **No such file or directory**)
   Active: inactive (dead)

TASK [infrastructure-agent-ansible : **setup agent service**] **********************
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Error when trying to enable newrelic-infra: rc=1 Failed to execute operation: No such file or directory\n"}
```

For more 
`fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "newrelic-infra", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "msg": "Error when trying to enable newrelic-infra: rc=1 Failed to execute operation: No such file or directory\n"}`

And
```
PLAY RECAP *********************************************************************
hostname : **ok=6**    changed=0    unreachable=0    failed=1
 
```

**Comment by habtamua** [comment] 2017-11-08 20:58
If this can also give an idea where the problem too

_$ sudo /usr/bin/newrelic-infra_

INFO[0000] New Relic Infrastructure Agent version 1.0.804 Creating Service (379.3µs)
INFO[0000] Agent service manager started successfully. (486.6µs)  service=newrelic-infra
INFO[0000] New Relic Infrastructure Agent version 1.0.804 Initializing (634.299µs)
INFO[0000] New Relic Infrastructure Agent version 1.0.804 Running (431.022062ms)
WARN[0000] unable to use SELinux                         error=exec: "sestatus": executable file not found in $PATH
WARN[0000] unable to use upstart                         error=exit status 1
ERRO[0000] Unable to read sysctl from /proc/sys/net/ipv6/conf/all/stable_secret, skipping: read /proc/sys/net/ipv6/conf/all/stable_secret: input/output error
ERRO[0000] Unable to read sysctl from /proc/sys/net/ipv6/conf/default/stable_secret, skipping: read /proc/sys/net/ipv6/conf/default/stable_secret: input/output error
ERRO[0000] Unable to read sysctl from /proc/sys/net/ipv6/conf/eth0/stable_secret, skipping: read /proc/sys/net/ipv6/conf/eth0/stable_secret: input/output error
ERRO[0000] executing data source                         data prefix=config/cassandra error=exit status 1 plugin name=cassandra-inventory stderr=time="2017-11-08T20:52:06Z" level=fatal msg="can't continue" error="open /etc/cassandra.yml: no such file or directory"

ERRO[0000] Unable to read sysctl from /proc/sys/net/ipv6/conf/lo/stable_secret, skipping: read /proc/sys/net/ipv6/conf/lo/stable_secret: input/output error
ERRO[0011] executing data source                         data prefix=config/cassandra error=exit status 1 plugin name=cassandra-inventory stderr=time="2017-11-08T20:52:18Z" level=fatal msg="can't continue" error="open /etc/cassandra.yml: no such file or directory"

^C2017/11/08 20:52:27 Orderly shutdown commenced
ERRO[0020] executing data source                         data prefix=services/cassandra_status error=signal: interrupt plugin name=cassandra stderr=
INFO[0020] Gracefully Exiting
INFO[0020] Agent service manager shutdown completed successfully.  service=newrelic-infra
****

**Comment by habtamua** [comment] 2017-11-08 23:42
I was able to make it work by uninstall the Infrastructure agent, use your package management tools, and run it again, it works.
`$ sudo apt-get remove newrelic-infra`

PLAY RECAP *********************************************************************
```
hostname1 : ok=7    changed=1    unreachable=0    failed=0
hostname2 : ok=7    changed=0    unreachable=0    failed=0
hostname3 : ok=7    changed=0    unreachable=0    failed=0
hostname4 : ok=7    changed=0    unreachable=0    failed=0
```

**Comment by smith** [comment] 2017-12-13 04:33
> but recently i upgrade some boxes to Xenial Xerus (Ubuntu 16.04.3 LTS) which make the newrelic infrastructure to start failing or missing some library

@habtamua so from my understanding if failed because of an Ubuntu distro upgrade. If that's the case you did the right thing by reinstalling the agent.

The amount of variables that a distro upgrade can introduce is probably too high to be able to troubleshoot and reproduce this effectively.

I'd say that the agent ideally shouldn't fail in this situation, but if it does there's probably not much we can do other than reinstalling.

Closing this issue. Please reopen if you continue to have problems or if I've misunderstood.

**Closed by smith** 2017-12-13 04:33 UTC
